In [25]:
import pandas as pd
import ast
import gzip
import numpy as np

In [26]:
import gzip
import json

rows = []

with gzip.open('steam_games.json.gz', 'r') as f:
        for line in f.readlines():
            data = json.loads(line)
            rows.append(data)

df = pd.DataFrame(rows)

In [27]:
print(pd.DataFrame(rows))

              publisher                                 genres  \
0                   NaN                                    NaN
1                   NaN                                    NaN
2                   NaN                                    NaN
3                   NaN                                    NaN
4                   NaN                                    NaN
...                 ...                                    ...
120440  Ghost_RUS Games  [Casual, Indie, Simulation, Strategy]
120441           Sacada              [Casual, Indie, Strategy]
120442     Laush Studio            [Indie, Racing, Simulation]
120443         SIXNAILS                        [Casual, Indie]
120444              NaN                                    NaN

                        app_name                     title  \
0                            NaN                       NaN
1                            NaN                       NaN
2                            NaN                       NaN
3                            NaN                       NaN
4                            NaN                       NaN
...                          ...                       ...
120440            Colony On Mars            Colony On Mars
120441  LOGistICAL: South Africa  LOGistICAL: South Africa
120442             Russian Roads             Russian Roads
120443       EXIT 2 - Directions       EXIT 2 - Directions
120444               Maze Run VR                       NaN

                                                      url release_date  \
0                                                     NaN          NaN
1                                                     NaN          NaN
2                                                     NaN          NaN
3                                                     NaN          NaN
4                                                     NaN          NaN
...                                                   ...          ...
120440  http://store.steampowered.com/app/773640/Colon...   2018-01-04
120441  http://store.steampowered.com/app/733530/LOGis...   2018-01-04
120442  http://store.steampowered.com/app/610660/Russi...   2018-01-04
120443  http://store.steampowered.com/app/658870/EXIT_...   2017-09-02
120444  http://store.steampowered.com/app/681550/Maze_...          NaN

                                                     tags  \
0                                                     NaN
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
120440              [Strategy, Indie, Casual, Simulation]
120441                          [Strategy, Indie, Casual]
120442                        [Indie, Simulation, Racing]
120443  [Indie, Casual, Puzzle, Singleplayer, Atmosphe...
120444  [Early Access, Adventure, Indie, Action, Simul...

                                              reviews_url  \
0                                                     NaN
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
120440  http://steamcommunity.com/app/773640/reviews/?...
120441  http://steamcommunity.com/app/733530/reviews/?...
120442  http://steamcommunity.com/app/610660/reviews/?...
120443  http://steamcommunity.com/app/658870/reviews/?...
120444  http://steamcommunity.com/app/681550/reviews/?...

                                                    specs price early_access  \
0                                                     NaN   NaN          NaN
1                                                     NaN   NaN          NaN
2                                                     NaN   NaN          NaN
3                                                     NaN   NaN          NaN
4                                                     NaN   NaN          NaN
...                                                   ...   ...          ...
120440                [Single-player, Steam Achievements]  1.99        False
120441  [Single-player, Steam Achievements, Steam Clou...  4.99        False
120442  [Single-player, Steam Achievements, Steam Trad...  1.99        False
120443   [Single-player, Steam Achievements, Steam Cloud]  4.99        False
120444  [Single-player, Stats, Steam Leaderboards, HTC...  4.99         True

            id                 developer
0          NaN                       NaN
1          NaN                       NaN
2          NaN                       NaN
3          NaN                       NaN
4          NaN                       NaN
...        ...                       ...
120440  773640        Nikita "Ghost_RUS"
120441  733530                    Sacada
120442  610660  Laush Dmitriy Sergeevich
120443  658870             xropi,stev3ns
120444  681550                       NaN

[120445 rows x 13 columns]

In [28]:
df.to_csv("steam_games.csv", index= False)

In [30]:
games = pd.read_csv("steam_games.csv")

C:\Users\Silvanita\AppData\Local\Temp\ipykernel_16284\3628713135.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,12) have mixed types. Specify dtype option on import or set low_memory=False.
  games = pd.read_csv("steam_games.csv")

In [31]:
games.drop(columns=["url", "reviews_url"], inplace=True)

In [32]:
columns_to_drop = ["developer", "tags", "specs", "early_access"]
games.drop(columns=columns_to_drop, inplace=True)

In [33]:
games.dropna(how='all')

,publisher,genres,app_name,title,release_date,price,id
88310,Kotoshiro,"['Action', 'Casual', 'Indie', 'Simulation', 'S...",Lost Summoner Kitty,Lost Summoner Kitty,2018-01-04,4.99,761140.0
88311,"Making Fun, Inc.","['Free to Play', 'Indie', 'RPG', 'Strategy']",Ironbound,Ironbound,2018-01-04,Free To Play,643980.0
88312,Poolians.com,"['Casual', 'Free to Play', 'Indie', 'Simulatio...",Real Pool 3D - Poolians,Real Pool 3D - Poolians,2017-07-24,Free to Play,670290.0
88313,彼岸领域,"['Action', 'Adventure', 'Casual']",弹炸人2222,弹炸人2222,2017-12-07,0.99,767400.0
88314,NaN,NaN,Log Challenge,NaN,NaN,2.99,773570.0
...,...,...,...,...,...,...,...
120440,Ghost_RUS Games,"['Casual', 'Indie', 'Simulation', 'Strategy']",Colony On Mars,Colony On Mars,2018-01-04,1.99,773640.0
120441,Sacada,"['Casual', 'Indie', 'Strategy']",LOGistICAL: South Africa,LOGistICAL: South Africa,2018-01-04,4.99,733530.0
120442,Laush Studio,"['Indie', 'Racing', 'Simulation']",Russian Roads,Russian Roads,2018-01-04,1.99,610660.0
120443,SIXNAILS,"['Casual', 'Indie']",EXIT 2 - Directions,EXIT 2 - Directions,2017-09-02,4.99,658870.0
120444,NaN,NaN,Maze Run VR,NaN,NaN,4.99,681550.0

In [9]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120445 entries, 0 to 120444
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   publisher     24064 non-null  object
 1   genres        28852 non-null  object
 2   app_name      32133 non-null  object
 3   title         30085 non-null  object
 4   release_date  30068 non-null  object
 5   price         30758 non-null  object
 6   id            32133 non-null  float64
dtypes: float64(1), object(6)
memory usage: 6.4+ MB

In [10]:
df.to_csv("steam_games.csv", index= False)

In [11]:
games = pd.read_csv("steam_games.csv")

C:\Users\Silvanita\AppData\Local\Temp\ipykernel_16284\3628713135.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,12) have mixed types. Specify dtype option on import or set low_memory=False.
  games = pd.read_csv("steam_games.csv")

ITEMS:

In [12]:
import ast

In [13]:
# Leer el contenido del archivo australian_users_items.json
with open('australian_users_items.json', 'r', encoding='utf-8') as f:
    data = f.readlines()

records = [eval(line.strip()) for line in data]
import pandas as pd

In [34]:
df_user_items = pd.DataFrame(records)

In [15]:
# Eliminar la columna "steam_id"
df.drop("steam_id", axis=1, inplace=True)

# Guardar el DataFrame actualizado en el mismo archivo JSON
df.to_json("australian_users_items.json", orient="records", lines=True)

KeyError: "['steam_id'] not found in axis"

In [35]:
df_user_items

,user_id,item_id,item_name,playtime_forever,playtime_2weeks
0,76561197970982479,10,Counter-Strike,6,0.0
1,76561197970982479,20,Team Fortress Classic,0,0.0
2,76561197970982479,30,Day of Defeat,7,0.0
3,76561197970982479,40,Deathmatch Classic,0,0.0
4,76561197970982479,50,Half-Life: Opposing Force,0,0.0
...,...,...,...,...,...
9995,76561198051017916,318220,Enforcer: Police Crime Action,0,0.0
9996,76561198051017916,266030,DRAKERZ-Confrontation,0,0.0
9997,76561198051017916,319180,Platypus II,0,0.0
9998,76561198051017916,257630,Blast Em!,0,0.0
9999,76561198051017916,319510,Five Nights at Freddy's,8,0.0

In [17]:
# Usar explode para descomponer la lista y replicar filas de la columna 'items'
df_user_items =  df_user_items.explode('items', ignore_index=True)

KeyError: 'items'

In [18]:
# Normalizacion de JSON a DataFrame  de la columna 'items'
# from pandas import json_normalize, si no esta importado
from pandas import json_normalize
df_items2 = json_normalize(df_user_items['items'])

KeyError: 'items'

In [19]:
# DataFrame sobre el cual se realizara el trabajo
df_user_items = df_user_items.join(df_items2)

NameError: name 'df_items2' is not defined

In [100]:
df_user_items.head(5)

,user_id,item_id,item_name,playtime_forever,playtime_2weeks
0,76561197970982479,10,Counter-Strike,6,0.0
1,76561197970982479,20,Team Fortress Classic,0,0.0
2,76561197970982479,30,Day of Defeat,7,0.0
3,76561197970982479,40,Deathmatch Classic,0,0.0
4,76561197970982479,50,Half-Life: Opposing Force,0,0.0

In [20]:
# Elimino las columnas que no voy a usar
df_user_items = df_user_items.drop(columns = ['items_count' , 'user_url'])

KeyError: "['items_count', 'user_url'] not found in axis"

In [21]:
import pandas as pd

# Supongamos que df_user_items es tu DataFrame
# Eliminar filas con valores nulos y reemplazar el DataFrame original
df_user_items.dropna(inplace=True)

In [22]:
# Función para convertir valores a enteros o 0 si no son válidos
def convertir_a_entero(valor):
    try:
        valor_entero = int(float(valor))
        return valor_entero
    except (ValueError, TypeError):
        return 0  # Puedes cambiar 0 a otro valor predeterminado si lo prefieres

# Aplicar la función de conversión a la columna "playtime_forever"
df_user_items["playtime_forever"] = df_user_items["playtime_forever"].apply(convertir_a_entero)

# Ahora, el DataFrame df_user_items contiene la columna "playtime_forever" corregida.

In [23]:
df_user_items

,user_id,item_id,item_name,playtime_forever,playtime_2weeks
0,76561197970982479,10,Counter-Strike,6,0.0
1,76561197970982479,20,Team Fortress Classic,0,0.0
2,76561197970982479,30,Day of Defeat,7,0.0
3,76561197970982479,40,Deathmatch Classic,0,0.0
4,76561197970982479,50,Half-Life: Opposing Force,0,0.0
...,...,...,...,...,...
9995,76561198051017916,318220,Enforcer: Police Crime Action,0,0.0
9996,76561198051017916,266030,DRAKERZ-Confrontation,0,0.0
9997,76561198051017916,319180,Platypus II,0,0.0
9998,76561198051017916,257630,Blast Em!,0,0.0
9999,76561198051017916,319510,Five Nights at Freddy's,8,0.0

In [107]:
df_user_items.dropna(inplace=True)

In [109]:
df_user_items.to_csv("australian_user_items.csv", index= False)

In [110]:
df_user_items = pd.read_csv("australian_user_items.csv")

REVIEWS

In [36]:
import pandas as pd
from textblob import TextBlob

# Cargar el conjunto de datos "australian_user_reviews" en un DataFrame
df_australian_user_reviews = pd.read_csv("australian_user_reviews.csv")

In [37]:
df_australian_user_reviews

,user_id,user_url,reviews,sentiment_analysis
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,"[{'funny': '', 'posted': 'Posted November 5, 2...",1
1,js41637,http://steamcommunity.com/id/js41637,"[{'funny': '', 'posted': 'Posted June 24, 2014...",1
2,evcentric,http://steamcommunity.com/id/evcentric,"[{'funny': '', 'posted': 'Posted February 3.',...",1
3,doctr,http://steamcommunity.com/id/doctr,"[{'funny': '', 'posted': 'Posted October 14, 2...",1
4,maplemage,http://steamcommunity.com/id/maplemage,"[{'funny': '3 people found this review funny',...",1
...,...,...,...,...
25794,76561198306599751,http://steamcommunity.com/profiles/76561198306...,"[{'funny': '', 'posted': 'Posted May 31.', 'la...",1
25795,Ghoustik,http://steamcommunity.com/id/Ghoustik,"[{'funny': '', 'posted': 'Posted June 17.', 'l...",1
25796,76561198310819422,http://steamcommunity.com/profiles/76561198310...,"[{'funny': '1 person found this review funny',...",1
25797,76561198312638244,http://steamcommunity.com/profiles/76561198312...,"[{'funny': '', 'posted': 'Posted July 21.', 'l...",1
25798,LydiaMorley,http://steamcommunity.com/id/LydiaMorley,"[{'funny': '1 person found this review funny',...",1

ANALISIS DE SENTIMIENTO

In [38]:
# Función para realizar el análisis de sentimiento y asignar valores numéricos
def sentiment_to_numeric(text):
    if pd.isna(text):
        return 1  # Valor '1' para reseñas ausentes
    analysis = TextBlob(text)
    if analysis.sentiment.polarity < 0:
        return 0  # Reseña mala
    elif analysis.sentiment.polarity == 0:
        return 1  # Reseña neutral
    else:
        return 2  # Reseña positiva

# Aplicar la función a la columna 'user_reviews.review' y crear la nueva columna 'sentiment_analysis'
df_australian_user_reviews['sentiment_analysis'] = df_australian_user_reviews['reviews'].apply(sentiment_to_numeric)

# Eliminar la columna original 'user_reviews.review' si ya no se necesita
df_australian_user_reviews.drop('reviews', axis=1, inplace=True)

# Guardar el DataFrame actualizado en un nuevo archivo CSV 
df_australian_user_reviews.to_csv("australian_user_reviews_with_sentiment.csv", index=False)

In [39]:
df_australian_user_reviews.head(5)

,user_id,user_url,sentiment_analysis
0,76561197970982479,http://steamcommunity.com/profiles/76561197970...,2
1,js41637,http://steamcommunity.com/id/js41637,2
2,evcentric,http://steamcommunity.com/id/evcentric,2
3,doctr,http://steamcommunity.com/id/doctr,2
4,maplemage,http://steamcommunity.com/id/maplemage,2

DESARROLLO API
ENDPOINT

In [40]:
import pandas as pd

# Rutas a los archivos CSV originales
ruta_steam_games = "steam_games.csv"
ruta_australian_user_items = "australian_user_items.csv"

# Columnas que deseas incluir en el archivo "Consulta_final"
columnas_steam_games = ["id", "genres", "release_date"]
columnas_australian_user_items = ["item_id", "playtime_forever"]

# Leer los datos relevantes de ambos archivos
steam_games = pd.read_csv(ruta_steam_games, usecols=columnas_steam_games)
australian_user_items = pd.read_csv(ruta_australian_user_items, usecols=columnas_australian_user_items)

# Combinar los datos en un nuevo DataFrame
consulta_final = pd.concat([steam_games, australian_user_items], axis=1)

# Guardar el DataFrame en un nuevo archivo CSV
consulta_final.to_csv("Consulta_final.csv", index=False)

C:\Users\Silvanita\AppData\Local\Temp\ipykernel_16284\3643601845.py:12: DtypeWarning: Columns (1,5) have mixed types. Specify dtype option on import or set low_memory=False.
  steam_games = pd.read_csv(ruta_steam_games, usecols=columnas_steam_games)

In [41]:
# Eliminar filas con valores nulos en alguna columna
consulta_final_sin_nulos = consulta_final.dropna(how='any')

# Limitar el DataFrame a 20,000 filas
consulta_final = consulta_final_sin_nulos.head(20000)

# Guardar el DataFrame limitado en un nuevo archivo CSV
consulta_final.to_csv("Consulta_final.csv", index=False)

In [42]:
def PlayTimeGenre(genero):
    # Cargar los datos del archivo "Consulta_final.csv"
    consulta_final = pd.read_csv("Consulta_final.csv")

    # Filtrar los juegos relevantes por genero
    juegos_relevantes = consulta_final[consulta_final["genres"].str.contains(genero, case=False, na=False)]

    # Agrupar por anio y sumar las horas jugadas
    grouped_data = juegos_relevantes.groupby(juegos_relevantes["release_date"].str[:4])["playtime_forever"].sum().reset_index()

    # Encontrar el anio con más horas jugadas
    max_playtime_year = grouped_data.loc[grouped_data["playtime_forever"].idxmax()]["release_date"]

    return {"Anio de lanzamiento con más horas jugadas para el genero": int(max_playtime_year)}

EDA Y MODELO DE APRENDIZAJE AUTOMATICO

Carga de datos:

In [52]:
import pandas as pd

# Cargar el archivo original
df = pd.read_csv("australian_user_items.csv")

# Filtrar y seleccionar las filas que cumplen con los requisitos
df = df[df['user_id'].astype(str).str.isnumeric()]
df = df.dropna(subset=['user_id', 'item_id', 'item_name'])

# Reducir el tamaño del DataFrame a 10,000 datos
df = df.head(10000)

# Guardar el DataFrame en un nuevo archivo CSV
df.to_csv("user_juegos.csv", index=False)

 Creación de la Función de Recomendación: crearemos una función de recomendación basada en la similitud de coseno entre "user_id" y "item_id". Usaremos el archivo "user_juegos.csv" que hemos creado en la Parte 1.

In [54]:
from sklearn.metrics.pairwise import cosine_similarity

def recomendacion_usuario(usuario_id):
    # Cargar el archivo "user_juegos.csv"
    df = pd.read_csv("user_juegos.csv")

    # Filtrar el DataFrame para obtener el usuario dado
    usuario = df[df['user_id'] == usuario_id]

    if usuario.empty:
        return {"message": "Usuario no encontrado"}

    # Eliminar la columna de usuario temporalmente para calcular la similitud del coseno
    df_sin_usuario = df[df['user_id'] != usuario_id]

    # Calcular la similitud del coseno entre el usuario dado y todos los demás usuarios
    similitud = cosine_similarity(usuario[['user_id', 'item_id']].values, df_sin_usuario[['user_id', 'item_id']].values)

    # Obtener los índices de los usuarios más similares
    usuarios_similares_indices = similitud[0].argsort()[-5:][::-1]

    # Obtener los juegos preferidos por los usuarios similares
    juegos_recomendados = []
    for indice in usuarios_similares_indices:
        juegos_usuario_similar = df_sin_usuario[df_sin_usuario['user_id'] == df.iloc[indice]['user_id']]['item_name'].values
        juegos_recomendados.extend(juegos_usuario_similar)

    # Filtrar juegos que el usuario ya haya jugado
    juegos_recomendados = [juego for juego in juegos_recomendados if juego not in usuario['item_name'].values]

    # Tomar los primeros 5 juegos recomendados
    juegos_recomendados = juegos_recomendados[:5]

    return {"Recomendaciones para el usuario": usuario_id, "juegos_recomendados": juegos_recomendados}